# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_hvplot_bug/',
                'doc_host': 'https://{user}.github.io',
                'git_url': 'https://github.com/{user}/nbdev_hvplot_bug/',
                'lib_path': 'nbdev_hvplot_bug'},
  'syms': {'nbdev_hvplot_bug.core': {}}}
