"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['df']

# %% ../00_core.ipynb 2
import pandas as pd
import numpy as np
import hvplot.pandas


# %% ../00_core.ipynb 4
df = pd.DataFrame({"a": np.arange(10)})

